### PR TITLE
v1.0.0 cleanup

### PR DESCRIPTION
**Pull request by ProLoser**
Just going to use separate repos from now on. Way easier and cleaner this way.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Anything blocking this PR ? I think it's a good initiative and should be completed as soon as we can

**Comment by ProLoser** [comment]
@PowerKiKi the other repos don't have the code yet.

**Comment by PowerKiKi** [comment]
Will you be able to work on that ? or should we split the work somehow ? How did you plan things like automatic releases and Travis integration ?

**Comment by douglasduteil** [comment]
@ProLoser :tada: 
@PowerKiKi Pick me for automatic releases and Travis integration I will help ;)

**Comment by ProLoser** [comment]
@PowerKiKi honestly I didn't figure we need special 'builds' or 'releases' quite as much anymore since I wanted the modules to be kept separate, even while deployed. Most people with decent build systems bundle up all the vendor files together anyway. I just wanted to move the code of the still-relevant modules into their respective repos. I consigned a volunteer to help but he seems to have dropped off the map. I stubbed out blank repos for all the ones I felt were still relevant today (I also renamed ui-scroll to ui-virtualize as I felt it was more accurate and `scroll` might get reused too much elsewhere).

As for allocation of work? Uh... the sub-repos are not being used, so feel free to just dump code into them as you see fit. I would keep their build processes minimal however.

**Comment by ProLoser** [comment]
New repos:
```
+    "ui-virtualize": "angular-ui/ui-virtualize",
+    "ui-scrollpoint": "angular-ui/ui-scrollpoint",
+    "ui-event": "angular-ui/ui-event",
+    "ui-mask": "angular-ui/ui-mask",
+    "ui-validate": "angular-ui/ui-validate",
+    "ui-indeterminate": "angular-ui/ui-indeterminate",
+    "ui-uploader": "angular-ui/ui-uploader"
```

**Comment by ProLoser** [comment]
@PowerKiKi if you'd like to do it you're more than welcome, or wrangle up some other people and add them to the utils team. I'm super swamped atm so I just wanted to stub out some stuff of what I'd like to see.

**Comment by PowerKiKi** [comment]
i'm working on that ui-event, ui-indeterminate and ui-mask done. The rest is on the way...

**Comment by ProLoser** [comment]
That is awesome! I know there might be some complaints about having to
include multiple files but I think this is so commonly automated and just a
few of many libraries people use that I wouldn't even worry about it.

**Comment by PowerKiKi** [comment]
@mfeingold, @dhilt, we are in the process of splitting modules into their own repositories. Since ui-scroll/NGScroller already has its own repository on https://github.com/Hill30/NGScroller, I was wondering if you would be willing to move your existing repository under angular-ui organisation ? or if you'd rather keep the current way of working with two repositories ?

If you do, then maybe you could also consider @ProLoser suggestion to rename ui-scroll into ui-virtualize ?

**Comment by PowerKiKi** [comment]
IMHO the last thing to do to close this ticket is to split/move/rename ui-scroll/ng-scroll/ui-virtualize. So I'm waiting to get some kind of answer from ng-scroll team.

http://angular-ui.github.io/ was also updated to reflect the new organization of things.

**Comment by mfeingold** [comment]
Before ew move everything under your roof we need to understand a few things. The major part is that we do development in coffeescript and publish the transpiled javascript to ui-utils. With the new structure will it be acceptable to continue to do so?

As to the name - I am understand @ProLoser reservations on the name, but virtualize feels so nebulous and generic that it does not really explain anything. virtual-repeat? sliding repeat? not sure. Any other ideas? between what I can come up with I still like scroll better. May be it is just a habit :)

**Comment by ProLoser** [comment]
I would still prefer the name change to SOMETHING else because scroll is a far more impacted "nebulous" term than virtualize. I felt they both have the same degree of specificity. Utils alone has had a few other scrolling related directives. 

I suggested virtualize because I felt it describes more what the module _does_ and less about what causes it to happen (as I prefer to keep implementation specific grammar out of code as it's always subject to change). That said whatever name you land on I am (personally) fine with. 

As for how you run your project, I have always tried to allow all projects to be fully autonomous and free to run themselves how they see fit while I have seen my role to be more of a consulting capacity where I give advice. Coffeescript is fine, it would be nice to drop it or pick up es6 instead as this is a standard,but not mandatory. 

That said, I speak only for myself personally on all  these points , and others are free to disagree.

**Comment by PowerKiKi** [comment]
I have no opinion regarding the name. That's entirely up to you guys, but I just wanted to mention the existence of https://github.com/kamilkp/angular-vs-repeat.

As for coffeescript, I don't mind either, as long as your build system is able to produce and publish something in JS, then that's good enough for me. I would try however to avoid two repositories. I feel if you could have everything in a single repository, that would avoid a lot of confusion (eg: useless PR against JS)

**Comment by mfeingold** [comment]
Alright. We (the team) took a vote on the name. Here is our list starting from what we like best:
 * `ui-vrepeat` and `ui-vrepeat-viewport` (`v` stands for virtual)
 * `ui-virtual-repeat` and `ui-virtual-repeat-viewport` (too verbose)
 *  `ui-repeat` and `ui-repeat-viewport` (is it too bold?)
 It goes downhill from here to 'dynamic-list` `virtual-array` and somesuch
I am still not too happy about going through another round of renaming. I would like to find a way to keep the old name at least for a while as an alias.

What do you think guys?

**Comment by ProLoser** [comment]
Keep the old name, you have my 2c.

**Comment by PowerKiKi** [comment]
So @mfeingold will you be able to move repositories by yourself, or would you need help for something ? If possible it would be best to do it "quickly" since ``ui-scroll`` is not really available anymore (or at least it looks like it's not available anymore).

**Comment by dhilt** [comment]
I plan to prepare our base repository (https://github.com/Hill30/NGScroller) to the transfer to the angular-ui during this day. Is it correct that we can leave the old name of the component? So the name of the module remains the same ("ui.scroll"), the name of the bower package will be "angular-ui-scroll" and the homepage will be "https://github.com/angular-ui/ui-scroll", right?

**Comment by PowerKiKi** [comment]
That's fine, yes. If you need help for anything, ping me.

**Comment by mfeingold** [comment]
Just created the ui-scroll repo. The code to be placed there is pretty much what we have now in the [Hill30 repo](https://github.com/Hill30/NGScroller) We will copy it to the new repo shortly. In the meantime you can review it in the Hill30 repo and tell us if there is anything you would like to be changed

**Comment by mfeingold** [comment]
How can I update the http://angular-ui.github.io/ page with the reference to the ui-scroll?

**Comment by compact** [comment]
If angular-ui/ui-scroll is the new location, I think the Hill30/NGScroller repo should be directly moved there in place of the current copy, so that the commits and issues will all be in one place.

**Comment by PowerKiKi** [comment]
I would tend to agree with @compact, you could transfer ownership and rename the existing repository if you care enough about issues. But that's entirely up to you.

Meanwhile I [added ui-scroll to Angular UI](https://github.com/angular-ui/angular-ui.github.com/commit/38b5348284fa3c5e6fd2e5624e7dd686b3a3ca1e) listing (doesn't matter if you destroy/recreate repository).

Also, I consider this issue closed.

**Comment by ProLoser** [comment]
Btw, wanted to say thanks for totally helping out and doing all the heavy lifting @PowerKiKi, after re-reading this thread I realized I misinterpreted your suggestion of splitting the work and ended up dumping it all on your shoulders lol.

**Comment by PowerKiKi** [comment]
lol :)

Nevermind, glad I was able to help. I am not able to contribute much to actual code, but I since I benefited from Angular UI efforts for my own projects, it's only fair that I give something back.

**Pull request closed without merging**
